spring:
  resources:
    static-locations: classpath:/
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .html
    content-type: text/html
    charset: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/my_database?useSSL=false&useUnicode=true&characterEncoding=utf-8&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 'admin'
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8083
  error:
    whitelabel:
      enabled: true